# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
import re
from openerp import api, fields, models


class CleanPersonalID(models.Model):
    """Allow to clean undesirable characters from personal id number"""
    _name = 'clean_personal_id'
    #_rec_name = ''
    unclean = fields.Char()
    clean = fields.Char(compute="_compute_clean", store=True, string='clean')

    @api.depends('unclean')
    @api.one
    def _compute_clean(self):
    	if self.unclean:
    		string = re.sub('[^0-9]+', '', self.unclean)
    		self.clean = string.lstrip('0')
    	else:
    		None
    	return True
    


